### ISSUE TITLE
Make 0.0.1 release

### ISSUE THREAD

**Issue by fjsj** [vintasoftware/django-ai-assistant#119]
## Description

- Publish  `django-ai-assistant` to PyPI
- Publish `django-ai-assistant-client` to npm
- Implement and document the release process
  - Management via GitHub actions
  - Sync versions between the two packages
  - Document the process in `contributing.md`

## Notes

- Make sure to create a tag (to trigger doc build).
- And to make a CHANGELOG.

**Comment by pamella** [comment]
- https://pypi.org/project/django-ai-assistant
- https://www.npmjs.com/package/django-ai-assistant-client
- https://vintasoftware.github.io/django-ai-assistant/0.0.1
