### ISSUE TITLE
Add a field to Thread to link the Assistant

### ISSUE THREAD

**Issue by pamella** [vintasoftware/django-ai-assistant#137]
## Description

Currently, the sidebar lists all threads without filtering them by a specific assistant.

## Proposed solution 

- Add a field to the Thread model to store the related Assistant ID
- Update the Thread's endpoint to support filtering by Assistant ID

**Comment by fjsj** [comment]
Solved by https://github.com/vintasoftware/django-ai-assistant/pull/179
